added task state changes
DBP-Rotov-Vitalii/TaskManager pull request #11
Opened 2022-10-05 17:18 UTC by DBP-Rotov-Vitalii

2022-10-05 19:28 UTC, greybutton requested changes
почему предыдущие реквесты не мержишь?

2022-10-05 19:28 UTC, greybutton commented on app/models/task.rb
> +      transition new_task: :in_development,
посмотри примеры как в одну строку из нескольких стейтов в один переход сделать https://github.com/state-machines/state_machines

2022-10-07 08:36 UTC, greybutton reviewed
почему предыдущие реквесты не мержишь в девелоп?

2022-10-10 12:46 UTC, DBP-Rotov-Vitalii commented
В упражнениях нигде не написано, что их надо мержить: я подумал, что или надо так оставить, или что мержить должен ревьюэр.

2022-10-10 12:47 UTC, DBP-Rotov-Vitalii commented
Мне теперь как это сделать? Мержить сначала этот в предыдущую ветку или сначала самый первый в девелоп?

2022-10-10 14:17 UTC, greybutton commented
по порядку с самого первого реквеста, каждую ветку нужно замержить в девелоп

2022-10-10 15:22 UTC, greybutton approved these changes

2022-10-11 16:49 UTC, merged